version: '3.1'

services:

  db:
    image: postgres:15
    container_name: pg
    restart: always
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
      POSTGRES_DB: pg